-------------------------------DROP TABLAS ----------------------------

IF OBJECT_ID('PUNTOZIP.ROLES') IS NOT NULL
DROP TABLE [PUNTOZIP].ROLES
GO

IF OBJECT_ID('PUNTOZIP.ROLES_FUNCIONES') IS NOT NULL
DROP TABLE [PUNTOZIP].ROLES_FUNCIONES
GO

IF OBJECT_ID('PUNTOZIP.ROLES_USUARIOS') IS NOT NULL
DROP TABLE [PUNTOZIP].ROLES_USUARIOS
GO

IF OBJECT_ID('PUNTOZIP.USUARIOS') IS NOT NULL
DROP TABLE [PUNTOZIP].USUARIOS
GO

IF OBJECT_ID('PUNTOZIP.FUNCIONES') IS NOT NULL
DROP TABLE [PUNTOZIP].FUNCIONES
GO

IF OBJECT_ID('PUNTOZIP.HOTELES') IS NOT NULL
DROP TABLE [PUNTOZIP].HOTELES
GO

IF OBJECT_ID('PUNTOZIP.PERIODO_HOTELES') IS NOT NULL
DROP TABLE [PUNTOZIP].PERIODO_HOTELES
GO

IF OBJECT_ID('PUNTOZIP.REGIMENES_HOTELES') IS NOT NULL
DROP TABLE [PUNTOZIP].REGIMENES_HOTELES
GO

IF OBJECT_ID('PUNTOZIP.REGIMEN') IS NOT NULL
DROP TABLE [PUNTOZIP].REGIMEN
GO

IF OBJECT_ID('PUNTOZIP.HABITACIONES') IS NOT NULL
DROP TABLE [PUNTOZIP].HABITACIONES
GO

IF OBJECT_ID('PUNTOZIP.TIPO_HABITACION') IS NOT NULL
DROP TABLE [PUNTOZIP].TIPO_HABITACION
GO

IF OBJECT_ID('PUNTOZIP.VISTA_HOTEL') IS NOT NULL
DROP TABLE [PUNTOZIP].VISTA_HOTEL
GO

IF OBJECT_ID('PUNTOZIP.RESERVAS_HABITACIONES') IS NOT NULL
DROP TABLE [PUNTOZIP].RESERVAS_HABITACIONES
GO

IF OBJECT_ID('PUNTOZIP.RESERVAS') IS NOT NULL
DROP TABLE [PUNTOZIP].RESERVAS
GO

IF OBJECT_ID('PUNTOZIP.CLIENTES') IS NOT NULL
DROP TABLE [PUNTOZIP].CLIENTES
GO

IF OBJECT_ID('PUNTOZIP.RESERVAS_CLIENTES') IS NOT NULL
DROP TABLE [PUNTOZIP].RESERVAS_CLIENTES
GO

IF OBJECT_ID('PUNTOZIP.ESTADO_RESERVA') IS NOT NULL
DROP TABLE [PUNTOZIP].ESTADO_RESERVA
GO

IF OBJECT_ID('PUNTOZIP.ESTADIA') IS NOT NULL
DROP TABLE [PUNTOZIP].ESTADIA
GO

IF OBJECT_ID('PUNTOZIP.CONSUMIBLES') IS NOT NULL
DROP TABLE [PUNTOZIP].CONSUMIBLES
GO

IF OBJECT_ID('PUNTOZIP.FACTURA') IS NOT NULL
DROP TABLE [PUNTOZIP].FACTURA
GO

IF OBJECT_ID('PUNTOZIP.ITEMS_FACTURA_ESTADIA') IS NOT NULL
DROP TABLE [PUNTOZIP].ITEMS_FACTURA_ESTADIA
GO

IF OBJECT_ID('PUNTOZIP.ITEMS_CONSUMIBLES') IS NOT NULL
DROP TABLE [PUNTOZIP].ITEMS_CONSUMIBLES
GO

------------------------------DROP SCHEMA------------------------------------
IF SCHEMA_ID('PUNTOZIP') IS NOT NULL
DROP SCHEMA [PUNTOZIP]
GO


CREATE SCHEMA [PUNTO_ZIP]
GO